package uk.ac.tees.m2081433.swimritemanagementsuite.model;

/**
 *
 * @author Bedford
 */
public enum SwimmingLevel {
    MOMS_AND_DUCKS, DUCKS, BEGINNERS, 
    GRADE_1_MINUS, GRADE_1, GRADE_1_PLUS, 
    GRADE_2_MINUS, GRADE_2, GRADE_2_PLUS,
    GRADE_3_MINUS, GRADE_3, GRADE_3_PLUS, 
    GRADE_4_MINUS, GRADE_4, GRADE_4_PLUS, 
    GRADE_5_MINUS, GRADE_5, GRADE_5_PLUS,
    GRADE_6_MINUS, GRADE_6, GRADE_6_PLUS, 
    GRADE_7_MINUS, GRADE_7, GRADE_7_PLUS, 
    GRADE_8_MINUS, GRADE_8, GRADE_8_PLUS,
    GRADE_9_MINUS, GRADE_9, GRADE_9_PLUS, 
    HONOURS
}
